"""Add profile data model and friendship relationship

Revision ID: 4fa351055522
Revises: 
Create Date: 2024-09-06 17:36:59.905806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fa351055522'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_city'), 'profiles', ['city'], unique=False)
    op.create_index(op.f('ix_profiles_first_name'), 'profiles', ['first_name'], unique=False)
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_index(op.f('ix_profiles_state'), 'profiles', ['state'], unique=False)
    op.create_index(op.f('ix_profiles_zipcode'), 'profiles', ['zipcode'], unique=False)
    op.create_table('friendship',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('profile_id', 'friend_id')
    )
    op.create_index(op.f('ix_friendship_friend_id'), 'friendship', ['friend_id'], unique=False)
    op.create_index(op.f('ix_friendship_profile_id'), 'friendship', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friendship_profile_id'), table_name='friendship')
    op.drop_index(op.f('ix_friendship_friend_id'), table_name='friendship')
    op.drop_table('friendship')
    op.drop_index(op.f('ix_profiles_zipcode'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_state'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_first_name'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_city'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
